language: node_js
dist: focal

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      name: lint
      script: npm run lint

    - &test
      stage: test
      name: test-node8
      node_js: '8'
      script:
        - npm run test:unit
        - npm run test:e2e
      after_script: npm run publish-coverage

    - <<: *test
      name: test-node10
      node_js: '10'
    - <<: *test
      name: test-node12
      node_js: '12'
    - <<: *test
      name: test-node14
      node_js: '14'
    - <<: *test
      name: test-node16
      node_js: '16'
    - <<: *test
      name: test-node18
      node_js: '18'

cache: npm
