# 🪦 Deprecation in progress, see .github/workflows/ci.yml
language: node_js
dist: focal

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      name: lint
      script: npm run lint

    - &test
      stage: test
      name: test-node16
      node_js: '16'
      script:
        - npm run test:unit
        - npm run test:e2e
      after_script: npm run publish-coverage
    - <<: *test
      name: test-node18
      node_js: '18'
    - <<: *test
      name: test-node20
      node_js: '20'
    - <<: *test
      name: test-node22
      node_js: '22'
    - <<: *test
      name: test-node24
      node_js: '24'

cache: npm
